// Generated by CoffeeScript 1.3.3
(function() {
  var Tank,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Tank = (function(_super) {

    __extends(Tank, _super);

    function Tank(map) {
      this.game = enchant.Game.instance;
      this.set(this.game.assets[this.game.CONST.MODEL_TANK]);
    }

    return Tank;

  })(Sprite3D);

}).call(this);
